Update makefiles for Android Q and clang
Clang is the only host compiler that works for now, need to set
`TARGET_KERNEL_USE_CLANG := true`.

Clang version expected on Q is 9.0.6.

ccache seems to work so far, using the Ubuntu 18.04 package.

TODO: GCC for host compilation is still not working, possibly because
some directories are messed up or path_interposer doing strange things.
```
  HOSTCC  scripts/basic/fixdep
[...]/kernel/scripts/basic/fixdep.c:105:23:
  fatal error: sys/types.h: No such file or directory
 #include <sys/types.h>
```

TODO: Amend build guides to include perl as a prerequisite!
(Though probably installed by default on pretty much any machine)
https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-p-9-0-0#tutorial-step-2